Bimba Dev/src/objects/Defect__c.object
<CustomObject>
    <description>TOOLKIT - This object represents a failure to meet a requirement.</description>
    <fields>
        <fullName>Defect_Detected__c</fullName>
        <label>Defect Detected</label>
        <picklist>
            <picklistValues>
                <fullName>Requirement Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Go-Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regression Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit Testing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Detailed_Description__c</fullName>
        <label>Detailed Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Business - Ready to Assign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fix in Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can Not Reproduce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Salesforce.com Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Enhancement Consideration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Defect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/objects/IDC_Task__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents work assigned to an offshore team.</description>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <label>Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Build_Task_Type__c</fullName>
        <label>Build Task Type</label>
        <picklist>
            <controllingField>Task_Type__c</controllingField>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Defect_Description__c</fullName>
        <label>Defect Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Defect_Found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defect Found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Defect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defect</label>
        <referenceTo>Defect__c</referenceTo>
        <relationshipLabel>IDC Tasks</relationshipLabel>
        <relationshipName>IDC_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDC_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IDC Task</label>
        <referenceTo>IDC_Task__c</referenceTo>
        <relationshipLabel>IDC Tasks</relationshipLabel>
        <relationshipName>IDC_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <formula>Request__r.Client_Request_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>IDC Tasks</relationshipLabel>
        <relationshipName>IDC_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Test Script</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Efforts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Track__c</fullName>
        <label>Track</label>
        <picklist>
            <picklistValues>
                <fullName>Track 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IDC Task</label>
    <nameField>
        <displayFormat>IDCTask-{0000000000}</displayFormat>
        <label>IDC Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IDC Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/objects/PMO_CreateDefect__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Create_Defect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Defect?</label>
        <type>Checkbox</type>
    </fields>
    <label>PMO_CreateDefect</label>
</CustomObject>

Bimba Dev/src/objects/PMO_TaskAssignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Owner_Queue__c</fullName>
        <label>Owner/Queue</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preceding_Task__c</fullName>
        <label>Preceding Task</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PMO_TaskAssignment</label>
</CustomObject>

Bimba Dev/src/objects/Request__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <fields>
        <fullName>Related_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this field to link duplicate requirements together or to group similar requirements.</inlineHelpText>
        <label>Related Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>CRM_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Identify: Submit for Business Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identify: Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approve: Approved to Deploy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: SIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Build Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Test Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Deployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/classes/PMO_Task_Assignment.cls
/*
    CREATED BY      CREATED DATE    DESCRIPTION
    -----------------------------------------------------------------------
    puneet aggarwal   02/04/2012    Helper class to create task based on custom setting 
                                    PMO_TaskAssignment

*/  
public  class PMO_Task_Assignment {
    
    public static void PMO_Task_Assignment(List<IDC_Task__c> lstTask){
        
        // Map to get task order vs. custom setting value               
        Map<String, PMO_TaskAssignment__c> alltasks = PMO_TaskAssignment__c.getAll();  
        
        // Map to get values to create defect               
        Map<String, PMO_CreateDefect__c> alldefects = PMO_CreateDefect__c.getAll();
        
        // Map to get task type vs completed IDC Task
        Map<String, IDC_Task__c> tasks = new Map<String, IDC_Task__c>();
        
        // List of new Task Types
        List<string> lstnewtasktype = new List<string>();
        
        // List of completed IDC Tasks
        List<IDC_Task__c> lstexistingTask = new List<IDC_Task__c>();
         
        // List of new IDC Tasks
        List<IDC_Task__c> lstnewTask = new List<IDC_Task__c>();
        
        // Creating a Map of Task type and completed IDC Task
        for(IDC_Task__c t: lstTask) {           
            
            if(alltasks.containskey(t.Task_Type__c)){
                
                tasks.put(PMO_TaskAssignment__c.getInstance(t.task_type__c).Task__c,t);
            }               
        }
        
        // Looping through all values in custom setting and creating list of new task types as well as completed tasks in same order
        for(PMO_TaskAssignment__c task : alltasks.values()) {
            
            if(tasks.containskey(PMO_TaskAssignment__c.getInstance(task.name).Preceding_Task__c)){
                                
                lstnewtasktype.add(PMO_TaskAssignment__c.getInstance(task.name).Task__c);
                lstexistingTask.add(tasks.get(PMO_TaskAssignment__c.getInstance(task.name).Preceding_Task__c));
            }
        }
        
        List<Defect__c> lstdefect = new List<Defect__c>(); 
        // Creating new tasks and adding them in the list
        for(integer counter=0;counter<lstnewtasktype.size();counter++){
            
            if(lstnewtasktype[counter] != system.label.PMO_Task_CodeReview || (lstnewtasktype[counter] == system.label.PMO_Task_CodeReview && lstexistingTask[counter].Build_Task_Type__c == system.label.PMO_TaskType_Customization)){
                IDC_Task__c IDCTask = new IDC_Task__c();
                //if(!TL.isEmpty())
                if(PMO_TaskAssignment__c.getInstance(lstnewtasktype[counter]).Owner_Queue__c != null){
        
                    IDCTask.OwnerId = PMO_TaskAssignment__c.getInstance(lstnewtasktype[counter]).Owner_Queue__c;
                }
                
                IDCTask.Assigned_Date__c = system.today();
                IDCTask.Task_Type__c = lstnewtasktype[counter];                      
                IDCTask.IDC_Task__c = lstexistingTask[counter].id;
                IDCTask.Track__c = lstexistingTask[counter].Track__c;
                IDCTask.Request__c = lstexistingTask[counter].Request__c;
                
                if((lstexistingTask[counter].Defect_Found__c == true && (lstexistingTask[counter].Task_Type__c.contains(system.label.PMO_Task_Review) || lstexistingTask[counter].Task_Type__c.contains(system.label.PMO_Task_Execution))) || (!lstexistingTask[counter].Task_Type__c.contains(system.label.PMO_Task_Review) && !lstexistingTask[counter].Task_Type__c.contains(system.label.PMO_Task_Execution)))
                lstnewtask.add(IDCTask); 
                
            }
            try{
                if( lstexistingTask[counter].Defect_Found__c == true && lstexistingTask[counter].Defect_Description__c != null
                           && PMO_CreateDefect__c.getInstance(lstexistingTask[counter].Task_Type__c).Create_Defect__c == true){
                   Defect__c dfct = new Defect__c();
                   Dfct.subject__c = system.label.PMO_Defect_Subject + lstexistingTask[counter].Request_Name__c;
                   Dfct.status__c = system.label.PMO_Defect_Open;
                   Dfct.Defect_Detected__c = lstexistingTask[counter].Task_Type__c;
                   Dfct.Detailed_Description__c = lstexistingTask[counter].Defect_Description__c;
                   if(lstexistingTask[counter].Request__c != null)
                        Dfct.Related_Request__c = lstexistingTask[counter].Request__c;
                   lstdefect.add(Dfct);
                  
                }  
           }
           catch(exception ex){
                 ex.setMessage(system.label.PMO_Task_Error);
           }
        }
        
        // insert the list 
        if(!lstnewtask.isEmpty()) {
            try {
                insert lstnewtask;
                insert lstdefect;
            }
            catch(DMLException ex){
                ex.setMessage(system.label.PMO_Task_Error);
            }
        }
        
   }
  
}