Bimba Dev/src/objects/IDC_Task__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents work assigned to an offshore team.</description>
    <fields>
        <fullName>Actual_LOE__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual LOE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IDC_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IDC Task</label>
        <referenceTo>IDC_Task__c</referenceTo>
        <relationshipLabel>IDC Tasks</relationshipLabel>
        <relationshipName>IDC_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_LOE__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Planned LOE</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>IDC Tasks</relationshipLabel>
        <relationshipName>IDC_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Script Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect Fix - Test Script</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM Efforts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IDC Task</label>
    <nameField>
        <displayFormat>IDCTask-{0000000000}</displayFormat>
        <label>IDC Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IDC Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/objects/Release__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release #</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Green: Milestone completion on target
Yellow: Milestone completion at risk
Red: Milestone completion planned to be missed or missed</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/objects/Request__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <fields>
        <fullName>Adapt__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated for Adaptation and Ongoing Support.</description>
        <inlineHelpText>Number of days estimated for Adaptation and Ongoing Support.</inlineHelpText>
        <label>Adapt &amp; Ongoing Support</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BUT__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated to complete Build and Unit Test phase.</description>
        <inlineHelpText>Number of days estimated to complete Build and Unit Test phase.</inlineHelpText>
        <label>Build</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Reason Closed/Deferred Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Des__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated for the Design phase.</description>
        <inlineHelpText>Number of days estimated for the Design phase.</inlineHelpText>
        <label>Design</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
        <label>Committed Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Req__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated for Requirement Gathering.</description>
        <inlineHelpText>Number of days estimated for Requirement Gathering.</inlineHelpText>
        <label>Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Title__c</fullName>
        <description>Captures the requirement title</description>
        <inlineHelpText>Captures the requirement title</inlineHelpText>
        <label>Request Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SIT__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated for completing SIT.</description>
        <inlineHelpText>Number of days estimated for completing SIT.</inlineHelpText>
        <label>Test</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Identify: New Requirement</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Identify: Submit for Business Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identify: Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidate: Approve to Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidate: Level of Effort Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approve: Approved to Deploy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: SIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Build Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release: Test Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Deployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close: Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrnDep__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated for Training and Deploying.</description>
        <inlineHelpText>Number of days estimated for Training and Deploying.</inlineHelpText>
        <label>Deploy</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UAT__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of days estimated to complete UAT.</description>
        <inlineHelpText>Number of days estimated to complete UAT.</inlineHelpText>
        <label>UAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Bimba Dev/src/classes/Test_PMO_Task_Assignment.cls
@isTest
private class Test_PMO_Task_Assignment {

    public testMethod static void testAllTriggers() {
        //Xcel_PMO_Tgr_Requirement_After
        //Xcel_PMO_Tgr_Requirement_UpdateLastTrackedChange
        
        User us = [select id from User limit 1];
         IDC_Task__c idcTask4 = new IDC_Task__c();
        idcTask4.Task_Type__c = 'Design';
        idcTask4.Planned_LOE__c = 1.00;
            idcTask4.OwnerId  = us.id;
        idcTask4.Start_Date__c = System.today();
        idcTask4.status__c = 'Re-assigned';
        insert idcTask4;
        idcTask4.End_Date__c = System.today();
        idcTask4.Actual_LOE__c = 1.00 ;
        idcTask4.Comments__c = 'Dev complete' ;
       
        idcTask4.status__c = 'Completed';
        update idcTask4; 
                
    }
    
    public testMethod static void testUpdateReleaseLOEOnRequestChangeTrigger() {
    
        Release__c rel = new Release__c();
        rel.Name = 'testRelease';
        insert rel;
        
        Request__c req = new Request__c();
        req.Request_Title__c = 'testRequest';
        req.Release__c = rel.Id;
        req.Req__c = 1;
        req.Des__c = 1;
        req.BUT__c = 1;
        req.SIT__c = 1;
        req.UAT__c = 1;
        req.TrnDep__c = 1;
        req.Adapt__c = 1;
        insert req;
        
        req.Req__c = 2;
        req.Des__c = 2;
        req.BUT__c = 2;
        req.SIT__c = 2;
        req.UAT__c = 2;
        req.TrnDep__c = 2;
        req.Adapt__c = 2;
        update req;
        
        delete req;
    
    }
    
}